### ISSUE TITLE
Using a custom Axios instance config

### ISSUE THREAD

**Issue by lockr7** [astahmer/openapi-zod-client#101]
As far as I can tell, this seems like a nice alternative to openapi-typescript-codegen if I want type safety. I'm curious if it's possible to use a custom axios instance config?

https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/custom-request-file.md
https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/axios-support.md

**Comment by astahmer** [comment]
Hey, this is out of scope for the `openapi-zod-client` library but you should be able to do just that with [zodios v11](https://github.com/ecyrbe/zodios/pull/237)

**Comment by robotkutya** [comment]
@astahmer why not modify this to accept a custom axios instance?
https://github.com/astahmer/openapi-zod-client/blob/e1e58c5c57ff9bfc205bdce8e006c248ec9a67d7/lib/src/templates/default.hbs#L85

This is a pretty common scenario, in a production environment you probably want to add interceptors to your axios instance, etc. You can solve this by modifying the template, but it might not be the worst idea in the world for the library to handle it.
