### ISSUE TITLE
oneOf creates invalid zod object.

### ISSUE THREAD

**Issue by misl-smlz** [astahmer/openapi-zod-client#103]
When we create a zod client via `openapi-zod-client spec/openapi.json -o src/validation.ts` for the following [openapi.json](https://github.com/astahmer/openapi-zod-client/files/11078583/openapi.json.txt), it generates a wrong zod definition (`const TestObject = z.union([z.unknown(), z.unknown()])`).

Using **oneOf** in the openapi.json leads to that error.

**Comment by astahmer** [comment]
[here's the playground link](https://openapi-zod-client.vercel.app/?doc=N4KABBYEQPYA4FMB2BDOBLKAuaBmAdAAz4BMUANOJFOkgGYzZjAC%2Blk0AxjALZwxJkAFwDOTUBw5QRnABYIeKMTgmS1UACoIRQgPIAjAFYJOQ8VTWXoQgJ6ImsIybPsrlqACcEARwCu6LwATJgBtKDgPeABGKABdVzdJWEFdOlDgaC8-AIRgnDCI%2BDJYsDZmTJ9-INDwyLhcONL4i0TqQsQPIXRtc1a3WujevtaoW3scaSEPWgBzKBbhyDYFxeh2shUV1eoxhAcdaaQ5reHl7al2hs3z9139qdn5m4gWE6tXvo-LL5eEtZQhLJlMwTlAAPRCbRCAD6cABsiGiXCMB0iOGnm0-CQIh612eUBIhEIaOe0EC2k40zgXQEDgYHh4YAA7kowChOJwENTck9nj9Tn8%2Bhi-FCAEIwQI2EmrKDcJCQ%2BXSm5QNBwAA26E4APQAjBhhEtLxpPUMnkiiVxqkABIvGkJgBiMHcPgCYQiMGmhRKMFaHQGYymXmWjj80mh1bhxKRyTR-mvV5AA) for future reference btw

What do you expect the output to be ? 

also, if something is unsupported it would help if you could add a link to the official specs section showing how what's missing should be implemented 🙏

**Comment by misl-smlz** [comment]
Thank you for the playground link, I'm very new to zod (and your library). Sorry.

I've expected something like this:

```
const TestObject = z.object({ prop1: z.string(), prop2: z.string().optional(), prop3: z.string().optional() }).refine(
    data =>
        !(data.prop2 === undefined && data.prop3 === undefined),
    { message: "prop2 or prop3 is required" }
)
```

**Comment by astahmer** [comment]
ok got it ! this kind of output are not planned to be supported and I don't think this is a valid openapi input (having a schema object without a type, just with a `required`)
