### ISSUE TITLE
$ref inside requestBody is ignored

### ISSUE THREAD

**Issue by FakeGodd** [astahmer/openapi-zod-client#120]
When the `requestBody` object is using `$ref` to `#/components/requestBodies` the tool is not generating the correct schemas for the request body type. I'll share below 2 different openapi portions of the same file that one is working correctly and the other does not (_the rest of the file is equal_).

The "broken" object portion: 

```
 "requestBody": {
          "$ref": "#/components/requestBodies/PostdatedChequesListRequest"
        },
```

The working object portion:

```
 "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostdatedChequesListRequest"
              }
            }
          }
        },
```

any ideas why that is?

Thanks.

**Comment by astahmer** [comment]
It looks like requestBody.$ref isn't yet supported, feel free to open a PR !
it should be around [here](https://github.com/astahmer/openapi-zod-client/blob/dc16074f377492d1337ae55366ce54573865adc9/lib/src/getZodiosEndpointDefinitionList.ts#L165)
