### ISSUE TITLE
Content type with `charset` not supported

### ISSUE THREAD

**Issue by govizlora** [astahmer/openapi-zod-client#139]
Hi, thank you for making the tool!

In my first try to convert my OpenAPI spec, it fails to parse the below content

```
"requestBody": {
  "content": {
    "application/json;charset=UTF-8": {
      "schema": {
        "$ref": "#/components/schemas/Foo"
      }
    }
  },
}
```

After comparing with your input example, I replaced `application/json;charset=UTF-8` to `application/json`, and now it works perfectly.
 
Would be nice if it can support the content with `charset` specified, or at least throw an error to prompt the user to remove the `charset` part.

**Comment by astahmer** [comment]
hey, that's what the `isMediaTypeAllowed` option is for


https://github.com/astahmer/openapi-zod-client/blob/3cde9645a767061cb56548a86eba1a77e1756b86/lib/src/getZodiosEndpointDefinitionList.ts#L53-L58

also available as a CLI arg
  --media-type-expr <expr>  Pass an expression to determine which response content should be allowed
