### ISSUE TITLE
pastable is an unlicensed dependency

### ISSUE THREAD

**Issue by marcelotheodoro-8arm** [astahmer/openapi-zod-client#141]
This package is dependent on [pastable](https://www.npmjs.com/package/pastable), which doesn't provide a specific usage license. As is, this poses as a legal risk for people using `openapi-zod-client`.

I'd suggest: 
- removing `pastable` as a dependency from `openapi-zod-client` 
- or adding a license to `pastable`

**Comment by astahmer** [comment]
got it ! just added one using the MIT license template from github

**Comment by marcelotheodoro-8arm** [comment]
Great, thank you very much!
