### ISSUE TITLE
cannot disable with-alias in playground

### ISSUE THREAD

**Issue by scarf005** [astahmer/openapi-zod-client#169]
![image](https://github.com/astahmer/openapi-zod-client/assets/54838975/449d5de2-bb40-4c2c-af6c-6e5d2c2959e3)
![image](https://github.com/astahmer/openapi-zod-client/assets/54838975/cc888334-149a-400d-bce3-ae40562ac9e6)

**Comment by scarf005** [comment]
https://github.com/astahmer/openapi-zod-client/blob/a20153bd66f1f631c6aac5224a418a9e2f8b04c7/playground/src/components/OptionsForm.tsx#L22-L36

https://github.com/astahmer/openapi-zod-client/blob/4f4e3c746e13da31b6006068794f1c33b86e2797/playground/src/Playground/Playground.tsx#L635-L647

well, it was an expected behavior, however now i found new bug: it's not possible to disable `withAlias` in openapi-zod-client because i've set `--with-alias` flag to default to `true`, which means #166 effectively... makes no changes. will check on that.

**Comment by astahmer** [comment]
you're on fire ! thanks
