### ISSUE TITLE
[Feature Request] When using groupStrategy: tag-file, allow creation of common.ts file

### ISSUE THREAD

**Issue by imballinst** [astahmer/openapi-zod-client#186]
For example, at the moment if I add `Pet` to the `store` tag, it will result in something like this: https://github.com/imballinst/oas-typescript/blob/17-create-oas-typescriptaxios/packages/oas-typescript-axios/generated/generated/store.ts#L4-L33

```ts
const Order = z
  .object({
    id: z.number().int(),
    petId: z.number().int(),
    pet: Pet,
    quantity: z.number().int(),
    shipDate: z.string().datetime({ offset: true }),
    status: z.enum(['placed', 'approved', 'delivered']),
    complete: z.boolean()
  })
  .partial()
  .passthrough();
const Pet = z
  .object({
    id: z.number().int().optional(),
    name: z.string(),
    category: Category.optional(),
    photoUrls: z.array(z.string()),
    tags: z.array(Tag).optional(),
    status: z.enum(['available', 'pending', 'sold']).optional()
  })
  .passthrough();
const Category = z
  .object({ id: z.number().int(), name: z.string() })
  .partial()
  .passthrough();
const Tag = z
  .object({ id: z.number().int(), name: z.string() })
  .partial()
  .passthrough();
```

This duplication (along with the one in the `pet.ts` file is unnecessary. I think when we have types being referred more than once from different tags, we can add them to the `common.ts` file. So, in the case above, it will be like this:

```ts
import { Pet } from './common'

const Order = z
  .object({
    id: z.number().int(),
    petId: z.number().int(),
    pet: Pet,
    quantity: z.number().int(),
    shipDate: z.string().datetime({ offset: true }),
    status: z.enum(['placed', 'approved', 'delivered']),
    complete: z.boolean()
  })
  .partial()
  .passthrough();
```

and then in `pet.ts` file it will also import the `Pet` from `common.ts`. I kinda think this should be possible, considering we're already doing something similar for `groupStrategy: method-file`. Let me know what you think about it. Thanks!

**Comment by astahmer** [comment]
makes sense, feel free to send a PR ! 🙏

**Comment by imballinst** [comment]
Alrighty! I'll see what I can do, perhaps it will take a bit while since I have to learn the mechanisms and stuff first (if that's okay)
