### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by Richard87** [astahmer/openapi-zod-client#187]
Do you have any advice on how to deal with this error? 

I got the new error after adding a few endpoints to the api:
```text

./pages/me/profile.tsx:18:13
Type error: Type instantiation is excessively deep and possibly infinite.

  16 |   const onSaveName = async (e) => {
  17 |     try {
> 18 |       await apiClient.post("/api/members/change-name", {
     |             ^
  19 |         name: e.target.value,
  20 |         memberId: memberId
  21 |       })
- info Linting and checking validity of types ..%            
```

[openapi.yaml.zip](https://github.com/astahmer/openapi-zod-client/files/12140084/openapi.yaml.zip)

A short discussion about the issue here: https://github.com/microsoft/TypeScript/issues/34933

**Comment by astahmer** [comment]
Not sure but this seems more of a typescript / zodios issue rather than openapi-zod-client one ?

**Comment by jwyce** [comment]
seems like zodios (and typescript) has a limit for how complex your api can be in a single client: https://github.com/ecyrbe/zodios/issues/256. I don't know how we could solve this besides breaking up the generated client into multiple pieces like that issues suggests, which isn't ideal 🤔

**Comment by Richard87** [comment]
Yeah, i was just thinking about it and its probably a Zodios issue, but there is not many endpoints, probably 10-15 with 'flat' apis, no neste content, and absolutley no recursion 😕
