### ISSUE TITLE
Create and use new pastable release with license

### ISSUE THREAD

**Issue by ronaldcurtis** [astahmer/openapi-zod-client#191]
I just noticed that openapi-zod-client still has a dependency with no license ([pastable](https://github.com/astahmer/pastable)).

Would it be possible to:
-  Create a new release for the `pastable` dependency so that it includes the new [license](https://github.com/astahmer/pastable/commit/91b97e982b219294d3cc2f8740ab0c63bf4db5ca)?
- Create a new release for openapi-zod-client that uses the new version of pastable

That would make our legal team very happy 😸

**Comment by astahmer** [comment]
done here https://github.com/astahmer/openapi-zod-client/pull/192
