### ISSUE TITLE
Create and use new pastable release with license 

### ISSUE THREAD

**Issue by ronaldcurtis** [astahmer/openapi-zod-client#193]
Sorry to be a pain and re-open this [issue](https://github.com/astahmer/openapi-zod-client/issues/191) 🙏 😅  But it seems like we'll need to create a new tag for [pastable](https://github.com/astahmer/pastable), as the license was added after [v2.2.0](https://github.com/astahmer/pastable/releases/tag/v2.2.0).

[License added in May](https://github.com/astahmer/pastable/commit/91b97e982b219294d3cc2f8740ab0c63bf4db5ca)

**Comment by astahmer** [comment]
np, https://github.com/astahmer/openapi-zod-client/pull/194
