### ISSUE TITLE
Including passthrough() on schemas seems to mess up type inference

### ISSUE THREAD

**Issue by robdodson** [astahmer/openapi-zod-client#196]
**Version**: 1.10.2

When I hover over the generated types for a response object, they include wrapping generics. I mentioned this in the Zodios discord and @ecyrbe said that this looked wrong, and that the types should be inferred.

![image](https://github.com/astahmer/openapi-zod-client/assets/1066253/45e6dea1-3ddb-4290-a2d6-24258f276d3d)

I think my issue is related to this change: https://github.com/astahmer/openapi-zod-client/pull/163, which added `passthrough()` to the end of all object schemas. If I manually remove the `passthrough()`s, or use the version of `openapi-zod-client` prior to this change, then the issue goes away.

![image](https://github.com/astahmer/openapi-zod-client/assets/1066253/ab5e72b9-e8e0-420a-bd1e-96bedd300d84)

**Test case**:

```yaml
openapi: 3.0.3
info:
  title: Bills API
  description: "API spec for the Bill object"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
  - name: list
    description: View many Bills
paths:
  /bills:
    get:
      tags:
        - list
      summary: Fetch all bills
      description: Index endpoint for bills. Can also be used for search
      operationId: getBills
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - bills
                properties:
                  bills:
                    type: array
                    items:
                      $ref: "#/components/schemas/Bill"
components:
  schemas:
    Bill:
      type: object
      required:
        - id
        - schema_id
        - created_at
        - created_by
        - updated_at
        - updated_by
      properties:
        id:
          type: integer
          format: int64
        schema_id:
          type: string
          example: "bill_4328792"
        updated_at:
          type: string
          example: "2023-12-30 08:26:49.219717"
        updated_by:
          type: integer
          format: int64
        created_at:
          type: string
          example: "2020-07-27 08:26:49.219717"
        created_by:
          type: integer
          format: int64
```

```tsx
import * as React from "react";
import { ZodiosHooks } from "@zodios/react";
import { api } from "./openapi-client";

function App() {
  const hooks = new ZodiosHooks("myAPI", api);
  const { data } = hooks.useGetBills();

  return <div className="App"></div>;
}

export default App;
```

**Comment by ecyrbe** [comment]
@astahmer the thing is, passthrough seems to break type inference somehow because zod add `& [x: string]: unknown`. zod can't resolve the types when there are multiple objects with passthrough embedded.
i don't know a good solution here. zod could handle these case in their infer parser though. so maybe a better solution would be a fix on zod part ?

**Comment by ecyrbe** [comment]
@robdodson it seems that using a Simplify Helper fixes it. i pinged collin on twitter to check where it would be more valuable to add it. I would prefer Zod to add it rather than zodios. Because then if zod breaks it in another way, we'll have to change again inference on zodios.
