### ISSUE TITLE
zodios path parameters format

### ISSUE THREAD

**Issue by ecyrbe** [astahmer/openapi-zod-client#2]
Nice work here.

When looking at the generated code from the documentation, i see this :

```typescript
{
        method: "get",
        path: "/pets/{petId}",
        requestFormat: "json",
        response: variables["Pet"],
 },
```  
  
But zodios will not be able to infer `petId` and ask for the parameter. 
  
The correct generated format should be : 
```typescript
{
        method: "get",
        path: "/pets/:petId",
        requestFormat: "json",
        response: variables["Pet"],
 },
```

I did not check yet if this is just a typo in the docs.

**Comment by astahmer** [comment]
Hey, sorry for the delay I don't often check github notifications 😅 

nice catch ! i'll fix this asap, thank you for reporting this !
