### ISSUE TITLE
Move endpointRefiner function call location to just before the endpoint information being pushed to endpoints array

### ISSUE THREAD

**Issue by imballinst** [astahmer/openapi-zod-client#241]
Hello! I submitted this issue before https://github.com/astahmer/openapi-zod-client/issues/173 and the PR for adding that feature before.

However, I think I made a mistake. Instead of placing it here, where it's still "fresh":

https://github.com/astahmer/openapi-zod-client/blob/986126340ed00b4cd97e002d12c77622d98005bb/lib/src/getZodiosEndpointDefinitionList.ts#L154-L169

Perhaps it would be better to place it here, just before it's being pushed so that `endpointRefiner` can "inspect" all fields that are going to be used in the Handlebars template.

https://github.com/astahmer/openapi-zod-client/blob/986126340ed00b4cd97e002d12c77622d98005bb/lib/src/getZodiosEndpointDefinitionList.ts#L380-L384

What do you think? Aalso I'm unsure if it counts as a minor change or patch change, let me know. Thanks!

**Comment by astahmer** [comment]
yeah that makes sense, a patch is fine since it shouldnt break any current behaviour
