### ISSUE TITLE
Not able to parse allOf with an item has required only

### ISSUE THREAD

**Issue by C-ra-ZY** [astahmer/openapi-zod-client#260]
**Describe the bug**
We are attempting to modify the behavior of openapi-zod-client in [pull request 258](https://github.com/astahmer/openapi-zod-client/pull/258), with the expectation of correctly handling schemas within the allOf array that only contain the required field. 
The goal is to generate the correct type annotations for required fields and the corresponding Zod schema, like https://editor.swagger.io/ does(It can even automatically eliminate properties that cannot be resolved or located, show in the pic: abc).
![image](https://github.com/astahmer/openapi-zod-client/assets/12962297/674843aa-89e4-4ad8-9beb-bc0c771bcfc7)

However, after testing, it has been observed that the current code is not yet able to fully address this issue.
and more of that,  [pull request 258](https://github.com/astahmer/openapi-zod-client/pull/258) didn't take types generating into account. which should be supplemented.
![image](https://github.com/astahmer/openapi-zod-client/assets/12962297/0c1a357e-200d-477b-9920-6ea3717d4dcb)

**Minimal reproduction**
A simplified schema definition to reproduce this is like:
```
openapi: 3.0.3
info:
  title: User
  version: 1.0.0
paths:
  /user:
    get:
      responses:
        200:
          description: return user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'

components:
  schemas:
    user:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    userResponse:
      type: object
      properties:
        user:
          allOf:
            - $ref: '#/components/schemas/user'
            - required:
              - name
```
The generated client code:
```
import { makeApi, Zodios, type ZodiosOptions } from "@zodios/core";
import { z } from "zod";

type userResponse = Partial<{
    user: user & unknown;
}>;
type user = Partial<{
    name: string;
    email: string;
}>;

const user: z.ZodType<user> = z.object({ name: z.string(), email: z.string() }).passthrough();
const userResponse: z.ZodType<userResponse> = z
    .object({
        user: user.and(
            z
                .object({})
                .and(z.object({ name: z.unknown() }))
                .passthrough()
        ),
    })
    .passthrough();

export const schemas = {
    user,
    userResponse,
};

const endpoints = makeApi([
    {
        method: "get",
        path: "/user",
        requestFormat: "json",
        response: userResponse,
    },
]);

export const api = new Zodios(endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions) {
    return new Zodios(baseUrl, endpoints, options);
}
```
but the code will trigger an error:
![image](https://github.com/astahmer/openapi-zod-client/assets/12962297/3f4dd786-1006-4d0a-bc0f-1a2c85603184)
and the schema fail to require correctly property(even when delete the unnecessary .passthrough()):
![image](https://github.com/astahmer/openapi-zod-client/assets/12962297/ee084cdb-e814-40aa-831e-5cf2b4978474)

**Expected behavior**
we can generate types and schemas correctly like https://editor.swagger.io/.

**Additional context**
guys can easily check issue reproduction at https://github.com/C-ra-ZY/openapi-zod-client/tree/test-on-first-fix
run 
```
npx tsx test.ts
```
and see the generated test.client.ts

**Comment by marrowleaves** [comment]
@C-ra-ZY  Thanks for find my flaw in handling the `.passthrough()` for empty objects, but I don't this the proposed fix is a valid solution as it should not remove any `required` fields from the user spec.

As it's specified in [OpenAPI spec](https://swagger.io/specification/#:~:text=allOf%20takes%20an%20array%20of%20object%20definitions%20that%20are%20validated%20independently%20but%20together%20compose%20a%20single%20object.)
>  `allOf` takes an array of object definitions that are **validated independently** but together compose a single object.

The visual doc in https://editor.swagger.io/  has a misleading feature that it tries to merge `allOf` objects as I mentioned in [issue 257](https://github.com/astahmer/openapi-zod-client/issues/257#:~:text=(I%20believe%20they%20did%20some%20merge%20on%20the%20finally%20resolved%20schema)) and it actually fails to display `required` but `unknown` property(that seems just a bug)

A better fix might be to have an ad hoc case handling of `required` only objects by removing the `z.object({})` part and generating `z.object({ name: z.unknown() })` directly?
