### ISSUE TITLE
schema .passthrough() optional

### ISSUE THREAD

**Issue by ferdinand-varta** [astahmer/openapi-zod-client#302]
Right now every schema will be generated with the .passthrough() option. Could this be made optional? The tl;dr example does not include the passthrough currently.

**Comment by prastoin** [comment]
Hello @ferdinand-varta, unless I'm mistaken you might be interesting by the following flag `--additional-props-default-value`
```
  --additional-props-default-value  Set default value when additionalProperties is not provided. Default to true. (default: true)
```

**Comment by ferdinand-varta** [comment]
Thanks @prastoin that worked and i saw why one passthrough() still remains. Our openAPIspec has "additionalProperties: true" on that object.
