### ISSUE TITLE
[Question] Why is response z.void() ?

### ISSUE THREAD

**Issue by drexxdk** [astahmer/openapi-zod-client#56]
When i run: pnpx openapi-zod-client 'https://petstore.swagger.io/v2/swagger.json' -o './src/schemas/test.ts'

It gives 
{
    method: 'get',
    path: '/pet/:petId',
    description: `Returns a single pet`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'petId',
        type: 'Path',
        schema: z.unknown(),
      },
    ],
    response: z.void(),
    errors: [
      {
        status: 400,
        description: `Invalid ID supplied`,
        schema: z.void(),
      },
      {
        status: 404,
        description: `Pet not found`,
        schema: z.void(),
      },
    ],
  },

Why is response: z.void() ?

**Comment by astahmer** [comment]
this use swagger v2 and not openapi spec (v3.0+)
try converting it to v3, it should be fine

you can convert from v2 to v3 using [the official swagger playground](https://editor.swagger.io/)

[this is the result on the playground with v3](https://openapi-zod-client.vercel.app/?doc=PYBwpgdghiCWBcACAzAOgAyoIwChYQDNh4dFEAXWcgGzCQGUB3KAcxbACdEAFMcgZ3LAOYUogAmYfgGMOsEJWAQkAcgAqAC1j9E2xFET8oAWxC1DnAG6cefQcLAWO1jqjIBNYAFdE0qBEQCfHFEb3JEYwd9ACMwsTImVnYuKHCAbQ1ychB4AHpc-mY2TlRYYABdAApM7LyCouTS4ABKUK4lRDTYDmlUAhFIYElUCD4AGkQAYkKkziqanPyZ4tcy3O7pXOa3RAAxYXiKLR0jU1oJgE9vX39EL35Hcg1HGFhEAGswC8QAA35waSwKDUAC0nwuPwowAoUnCTxeXiewlgAC9UmUAkFqOROPxUCoxDiOMZ%2BAB5Aj0KywaR0RALOrLRprIkk3JiaRKchQaTkEhkMhgYxQWDUJCvHEmAACjJKZTE1GpkAefP50GMtIAgiBuc9EAAmDCHLwcUV0rKLXKMK2oGA6sCoYQsXIKmkQB78XIAGQAkgBhACiADl6P6QQbMJljNQxC5%2BBikFgMKgAGw4MAADyJ0GoABFgNJ%2BCrJDI5Ap43tgqFEREolBYtXEisxMbTfSlg1ZcAcA9nLiSCC7iakAtC-lwAIhCJUDLVsBcpY9TgBy3h%2Ba6uP7FOZ0154uuSxC0vEGraeOxMXZPJFMpEP6XBcnvgWDEwogrsbbAIxBms8C8wWVTIC9S2vJBdkrV9IhEI0hzNWp21mWcjxPJBN1EICpEvMslCQDVpBpfgdCET80LaSQOH4ZCTFpe5OHPTCQPLUlwA4dElB0OtX1ojhv0zThs3-Q9%2BQkBir3LcCIBCSDa3rcJvC4NCYNbNcEJWJocG1J4hMQXJx1yABvcdvXEABfXIvDMYAoHEb0hXYQDEBAYBBAcsh9204SBzPYSyH4LxjCFDgLiQCzqCs8QOICWA7PQnzQE4NiIGMkLLOs8DaEOMhtVY9UiQ8-kBxQxy%2BGMzL%2BXwJBNI0MqMJLMScMQb0c1CAhirhaELPEVJYp8xARAARy8bowHEJByA4Lwep8mRniFVyfPIC5wCQfAcWSGr%2BSIYlUhWiByGTAAWMqBsmwQACEhmCjaOT2yBeQ2shjC8bF5CgDhyFyLbjBBLquXm3qZsFKB-t6xyOHi97YCkEHQf0cRxCoDFgQAWT4azUmBh7YYoJbaUEOQIBYLHYeA%2Bqbw1eHEaUYEJAxqFHKgQj6Z7FxiZ8rE6DZ3rFuWwxxqfLmfNJ7Cbw5%2BnQvCwXhK%2BnbEGifA3ouY6pCct1oY2vV0HQGGRLqkXUK8fCpH4AhntCFjEqxm6cT2nWyBgMxqUS3IACt%2BBwwXAbmqXEAAEhEAhVEmXIOVMJQ7o9L3GdyLVYAAJRV9iwAJAGwGkY0qCu3qvLsScwAAfSgRENBBgdGDkHF4A3DaBxEayq7sMRdL4ByQEReb3PmnPyDKvyAsVpAAFUQF%2Bl4AgzbRKEJtqyohxLkruEfut4HvepO2ELvELPQeF0DP1CaIXbTuENFSY8wBGojoWiF54ZG%2Bn4T5hxrs5O6dYdl1nbdj3sf5KO7f5P7MAgdEAqGDqHVWEcCjSFmtHFeKdsYfydteXI6YowAP-oLIBICwEh2AGHUYe1I4wKBh6eBG0TrDVGhQCaU0yAiH%2BEnfKwkDpax1rvcs3oICWGBLAEITVDAWUdiNK2r9baIH0iZDarCDrsNEvrfeEBgDhCIF4SSojbriMkdI9AABWORes94ADVeG-QxIgDMNIRYaJtryCRUjU7pwrtvTybU0KF2LqXRA5cqB0GrrDWuYB67%2BJ8umEEHJJDsAgCCdeggQSxC3iCIqCSlbCSci5Mqncyrd17v5QKwVEAUxCAYUYjA2oP11IpXqc9rwL2suIFeytBob0uiDDhDUV4HyPjyI4Z9RiX3pjfOGkgQjEUflU0G1s35YyQX4FB39lBs0wb-YS2Cg54IIVAqOZC%2BAINhrM52aDRRLJId7FZgCA7rIgeHIh0DYE7PIHsnylCRDUPGpNZWjC1bMP5Kw-RWN2k3i4TwhUIR8Bt1XtjKZWiHHTTThnRaXc3F5w8U8LxPjK4hOzn1IJo0sX8jCREsAUSYlgGaXElJSTqJIBSU3PSQRJJnQuPQLk5B7gOXYPdbmrAfk5IBnkgeFZJI6BXjoaI3xBCpHuGVQFSBkbPUoGYRwkq2U6BBadG4AQhkgHBpYPh99GBUA0L4fBQoLDZW6iEfGT5KLVItrU6hDKGl2CZSyqVtqfIWtyn2bJx5qV83dRtCqiBmlBQ2rKxAbrVWIHVVIXp4R%2BmjOvo4G6cZyL3y2oEEURIKFkqGq8satCNqCAuLQJAX0NoZkspIQtHzYbLOxjzWkb1WKpOxr4kkACm2oX5oTNmkgCBF2xGKHhIo6wZXOZAfyACBxQFHdQcddDQY50kgLc5A53bUHEJ81W7oQaa21gC%2BRe8-JG0Iqbag5sErXhsdM85Bz5nu0Wec3ypzMYvv5N2-QHBW0%2Bw7T885azQHgPwZA252zcjkPvSAR2cyMSoPQZ7N9ADhJfpbVANtH7-0oZ8kB3B1zCECDuaQyDuydGHt-hG4FpiA3RtjbemFvd4XOKRRuFFRc0U128RXPxjcAk4uCXxnS9LghMrUDyjlLdMkSd9d5aaAqgpgWCCKuwctvjuRlce8s8qXpKooDyzVctHA6uAHqkZ3ijUmv7uat6lq%2BYEwPG4QeDwNr7iwBMfceoPOsGQIEYQMJBBPlQLPe1GIF5OtFWJnlZUvV8B9dioqGnYbBtDZhoWWmGriYPPTLERI1O5sGlQ2tS7fKLTLX54klb0zVtpO8krhhkNYzQz%2BjDWNsNsy-davta9E7fP3Wwo9hjyynoIibM2NSMQMa5Ssh98GFk4YbR%2B5rv6P1kHa6ti5wCrmgZuURiDUGZswc-igo5C3GsbeW61jb62Nt%2B0ucBjZYG9tvoeU8lhA3KMZaBdwmj%2B4Y3AjrVCsRdjtG9UkDqtOlritMacZnVjucHCopLlxjFvGvz8brnioTzcPqGRKqZST03UMyexXJ4Sfd8lKckuU8VjUcyaaGw1BObKOBun0IYJ85gyf8gm0oBenKV5MtKr1WLeUkVFSMtu5LN4qrhq%2B0gARwBWrjnpiIFnEACv5pGtD%2Bt53G2412mtOiv8ZZ2NWodHdTD%2BsUexhGkbxsL1XtYje3%2B0KieIKO8gubT6zuwJw2QPDIHNngZe6Rx5bNZtKAQ8cj9i2X2B8e7t4h9yw9vd%2BR9238vGo-dBXTwRnuRGu%2BB0gUHoMZEGKwnvTpSiVHeHUUXzRIPYXk%2BY3D31rx87giQGkcohx0nu7ciTnyfL5P90U4gYeo8OLlPwEcZVecLNPAq8YWmXIQvXrC9Qzqy8%2BAAHUjX7EqyL2z3qKLi-9ZLoNMvUjVRJlnxXyu%2BDxvPgM4iQzt84il6DF52uaGA4BnrrDF%2BqtMSsbtjKbobhbj1uSuQJvC4j5G7u-J7nBlHmElaIwCCF9CCC2JAESqNCcn7oLCZixJQOrBtihD7G5AbvZmurdhGpPnZieC1HPjPBtiquypQTjLzF1kTLdrrJXuWAwZ-rRvcMwY-NzvQr1nujov8p9ozt9iCnwroBABClNiXs3n-K3oirJgjiIEjuijxg3OjsugJljsYRhLQJXNJgePDpCuTgpgUjmGAJYXGgYBIU7vPNQpIC4Y0sfjlHFmfr6kVB3uCFfsOLimAQAYQb-J1r2rwcPn6uqJVPjmEQzE8HLvIUgJ0kocRN4XFprkVn-vVnHtzNQSAetCbsIEKGbntFAc8lIWQWXhnnfpkdnoofws1H5AXl-rDIgfYjorIoNgIR0k-jXn5moj0ZMsXv0Y4givAWQN3O4hxsjvxqjkYR6tipjusU3GhLkMIORK3M5APvpjYb6hMvYWPgUtwAujSPoAEPsTYJmm4XwOvs7pvpVDcWAKSBwORE0qdLAa0hkcMTeA8VwGYNyBmv5m3D0KfHGNPOIS8b0cXjMsgV-D7gQUDDhgngRlsqHt8eRGnpIYVgWkUZbn1hrM0TvFnvbueuNqFkoGoRHqiY%2Bj-C%2BiUSstiTtoRsniRviZwIST5JHhANHr7piT7JycHs9innyRwAKawjbi0cCQrjnkoTKWoTMaEuEkMKAdErEuQPEpdFSkkXLJdDsXnHsT8ZwAZKCcZCZITh3EPq4ucX-A4VTiENCTAozI4KCWpnTgzkqXsP5u0Til8g8DQt8OUTYE1DoIakvrGogAAHwAC8iAWAdxIQAAPCmVgJgIgKSPCDxLDLGjGSKJelEtevfJYmACLBsTzvSUlNQpyjKULpMVlCfgEbyokbSDaa2eVNfukYqYxA1A-uUk8H0hfBFIMo4AQHwCQr2USVrm8kWrrtEdjEKOmNFNOqmegFjMYPgJucYAmE1mUbdBUeAVUbLObkdD1qGY0b1AehXkOTeDSWNperzhrg3rYgAkKa7OibHoAfHvdvhlybidKZabKUybBocohv%2BauR%2BhKU9jyUKB6DKXKZSWDvfiqR0fnsIvOfyH0aXr1OXkMU%2BUgDKceMouMfXkDo3uoYcHkVYdyqcdis6b5K6YgE4S4Y5MaJ6WGT6bTk1P6aRYGVwMGQwruo8EFMoUblwNGYvsaukojNYNJaAaJQDvaBtIGMSuiMpf5kotEpGWpdQBqoatQGWZABWYUtwN6BYj%2BsILWWQO%2BQvAxV8eBTFu2WLkEf6j2akbLoOWTArs1EriwT6WOQmhOVfEZiJC4XhT-kuf-tNABb1HuRAAeUeTESeTJVjBAdJXUcJOJVbuRo%2BQFW0TRgIl0bheqYRT5MRXIQGeRWMaotRUibRRqQUOafgNYHtMIPAZyg6cxQkaxYIpcUgMzsaGzirp1XdMiHGrTuwQ5fwcJWNaztPkKCAMwfNSasWPTINP4JQKQQtU5Y2SVNwtNWGjeRJQBvqOhelq0S%2BY7u%2BYydBlBSyc%2BmyUlSsl%2BsAIfMfD7PUlTNmNwODCQVDFdRlbzIZZwTlatMgIuLMSxu3nAJ3l8N3r3mQOZD2CHHXDiPvk8BqC1vAf3v1Z2dxLkiNYgL6NjXGgqIIMwdxCWUviwLAF1coRCt%2BitnFPWQvLIEEjiM5riLjRoPja2lwqodAf8XAW0lnp6JPHTT2F0r9S1V%2BSiS9d7qyb-OyUAdQehmlr-DdvBUBUHohcRshbkPzRBbDHFTrvUbeVdQOkOsccJHbobKNg9fWVVRoWQIStqSSnqQaYkskqaejdxFjbzWAILTLRkmkkccTUiqTfyuTZTWHToDTXJK1PTfJYgEzSzeCtWDra8Z4UgDzd1ObfwBHZPKLYiH8S0lvFLa0ZHWnXcPLd9d0nYQgcib-D%2BfNhiWci%2Bpdrre2jiJ2uKYbYntySbdHObQKVbaSRdYVXfoOgqsVQovdXSRvgyZ%2BW-BqcJN7ZEpAKSjAf7RcEabSLSsHZjfpNxCeHaYcH1dYSTT2GTZTogAAOJP7cS%2Bkf0ngF0OpICcrm1MqBjUTuX%2BGeUJb%2BpX3APS6VQ35AnCXqC6hMFhUv6Tlv7TmznPDiBOZhncRpmZo4iBaExuDT15qFF1bFofWobUE8FknSGwwPkkUlWr1vnu2b22yQXHZq1vXnKa3YwIVJ4T0ehT0cNe6oEwXvVwWAVbYPY4kh4p7COwzynL17zUa56QPqg4UKiF40Vfnb01XoCDF1XCXm0UW14TEe197tz31x2P0J3P1CH3zx23UBmaB6B%2BD3EQDUDfBDLiDhy%2BmPxhTFBgoBDcTBZ2rr0NkpSjzm0gPURgMJFFTqP1bBp%2BVUmtFIOnzhX3xoOLyjyxWkMknkMrling14xxHV3nSAn%2BUKIOMhAf0t2K1TG0Uq2cNR7d08OUOgz8Pj0QYKPf4FO-5FM22XUgxKOMMKKqNKEf0VVaN4VkAEWe3p6GOZ6tEmONV15zMmqtXVVe1al726l5qwhH0n00pB38guWx2%2BpOMXHP2cVxZN2RHnNZ6uM6DuOhCePeOOC%2BOjD%2BO6iBPsDBMPOuA-3vHRVxYxN%2BFxPxYJMQM9jf3QNpG35pMuOIPUTP6JqRU%2BPOFxb5PEmDPLmgy8NUHcHlNz3kmKM3VO2YXBlJOaNQybMLMDHKOCHy3rPmNsNN5Nwh2BMVS31SZMUP2PNsXk2ejADZYf2rTQjjIXCCCCggt87UI8sQAQueoeXQuuKJNwtQOgwpaTTnXIvCWaCOBf1ouZpKsFGFMEtRElP64ksOZeXGnaiESMD7GpGpZwMlVGsMzOv7EVaIBKvKG%2BC0BvQwiZgWv4sJXk6dPEtlP2tkt0OgwMNGNMMu0O5r1vEb3YzPDWTqvYwAAaIIcc3UIIMte5jtBrJVfgZlOgLEdI8k%2BgZlwAjA98tOj81zKyRLoMwBp5QrKy0Ne0sNbMBb-o1Ww0-AIIGoBARIOGEao8gbg8agvo3izwAQQgnw48o7DCSGkj5ysRcbq2OVo8IIlA6oT1h2qtbTf5EjNrS21DpL57rTwpp227N7fdd7%2B7RFlLTzrRkzdTWr6oukjMhQvrMz9LFj59VpgTYQ9p1jVztjo%2Bz9or2Wr4TiIge0-rYrALgb0zxsk24TGbkTGHLAYQKr%2BVDRdtwCDtzLDUzDHhLuOjW9peGNnAhxUdC0jpBUQLT9gqSd3UXHGFrRLzhmSgXjUV3zjgrbfzmH98s%2BoT8rhHxdfN8HZHMBktHrCivHwh9TP1PIL8zTndzJXDGC0buGo9sjUpJGfT4tZDVr-IBV5LVJi9w64zJ6qbtJLDET4HmpRKvthzFKhpgdW8OA5n2k2yDkscCct5Hc1BDTunIuwNnAB1IMRKOs3bWVlR20NR5Ag7Wty0x5drtByVxsrAnMpTPaH7FN3UxHimmSMXOnbdWUCXkMd5PkfCqXmVql2VF5WXeVPkFBZXNB3WoS4jvURUvoVXPVhwK880VtDrS6XkGgyiwAg8JoC1X19XMWTXSXQa%2BBA3kNGX1RkB15kyE3NXv83ToFJG43a0PVAp-XtrsbhXoMGYJgSqSAvjbAUMG0IAi3QgK31AYNXBzaBNWMz75y5cDsEb9Wa2Q9gPMb5XT3sMYPL6Euv3y3JormHHpRvM%2Bdv8yPv8EPMGUPbWsPACF3cjJGWWAp817XBXQ31Te8Kum1s%2B4yecWMU6h5WMs686i6XPxUq69PJhm6vZ%2BPfX-qvh-IWW0XvMsXDXYMEM23yWu3D3hunXB3l5tRx3o31K%2BXj3gvXtI3YvxpWWhwMp0v3ZG38XCvoNIMbXuvqvZ5sM-b%2B0Wvnq%2BOtPtI%2B355mXR3G0u1e0bee3PbhZ3vh30lOXhLWgIAOY3UHvCP%2Bv7M3X73xbJ7xRrKHBA3NDybCi5FUa0qv8HPOsXknxmzs6MGuq2j-G3hzNnAlf7dZwcWcfJpwAwbH5w3MeoMRUapwk5t5vSAsvm31vLXwkdvQf6XofGvLvG0STTfWfoMQQFE5AQDSR9vg38RvUC6ggy-pXKva-laQoIos-97x%2BPrPxR-FXaSi3ow5-iP-I3EefgPaXavKzAZJjD-XXPv4fcN7fIMRUKrDwsORaPQFOQtcQiKNWrjjzgAABpL4GVGCJI1QivUYNNm1%2BJpJdCBcZYn31CDLFv%2B0sMKIwCurRRYMVAd%2BMXGRBohrw-3VcNkFHA440I04DsLOD2LLFcgyxcgdDwazxQ4ephdYkgExxvh62%2BKWGGsQ3BIBIgCMAgN8A3CBt3wKQfCHXh7hAA)

**Comment by drexxdk** [comment]
Thank you. That works
