### ISSUE TITLE
[Question] Whitelist / Blacklist endpoints?

### ISSUE THREAD

**Issue by rmortes** [astahmer/openapi-zod-client#58]
Hi! I was wondering if there was a way to whitelist / blacklist some endpoints / endpoint aliases using regular expressions, and if it made sense in this project. My use case would be the following:

Say you have to build a small webpage that connects to a really big, old, monolithic API with hundreds of endpoints, but you only had to consume a small subsection of those, say, `auth*` and `analytics`. If we had the ability to whitelist and/blacklist, we could run:

```sh
yarn run openapi-zod-client --w "^\/api\/v1\/auth.*$" --w "^\/api\/v1\/analytics.*$"
yarn run openapi-zod-client --wa "^apiV1Auth.*$" --w "^apiV1Analytics.*$"
```

(Just a proposal of syntax, regex expresiones may not work)

To generate a 1000 lines of code instead of 50000 lines, thus making the typescript language server run way faster and reducing out bundle size

**Comment by astahmer** [comment]
hey, there is an option that gets somewhat close to what you want

```sh
--group-strategy          groups endpoints by a given strategy, possible values are: 'none' | 'tag' | 'method' | 'tag-file' | 'method-file'
```

you can try it on the [playground](https://openapi-zod-client.vercel.app/)
![Screenshot 2022-12-26 at 09 49 23](https://user-images.githubusercontent.com/47224540/209527507-bacbc17d-901f-4e03-9779-73ea76cdf50a.png)

but if you need more specific filtering than this, I think it would be easy to do if you do it on the input (openapi doc as yaml/json) directly before running `openapi-zod-client`

- create a script `filter-doc.ts`
- you'd need to parse the openapi doc (we're using https://github.com/APIDevTools/swagger-parser for that internally)
- either write the file on disk & then you can just use like `yarn run tsx ./filter-doc.ts && yarn run openapi-zod-client ./input.yaml`
- or do it programatically ([example here](https://github.com/astahmer/openapi-zod-client/blob/4925ab30025c262771cac2b26009f66526e63b78/examples/basic/petstore-generator.ts)) and use the `generateZodClientFromOpenAPI` expose method from `openapi-zod-client` by passing your filtered `openApiDoc`
