### ISSUE TITLE
Unable to run with yarn

### ISSUE THREAD

**Issue by 1oglop1** [astahmer/openapi-zod-client#6]
Hi, am I doing anything wrong here?

```
$ yarn openapi-zod-client plugin-redoc-0.yaml

yarn run v1.22.19

Retrieving OpenAPI document from plugin-redoc-0.yaml
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open './src/template.hbs'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './src/template.hbs'
}

Node.js v18.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by astahmer** [comment]
Hey ! Sorry for this, you did nothing wrong here that's my bad the path was wrong, I just published a new version with a fix, this should be fine now (if not, you could use the "-t", which stands for template, argument of the CLI to provide a custom template path in the meantime)

https://github.com/astahmer/openapi-zod-client/commit/d23069e505f5799c1aa09fcc5f4a6cedd31f5d9d
