### ISSUE TITLE
Error `TypeError: schema.type.toLowerCase is not a function` when converting definition

### ISSUE THREAD

**Issue by JarnoRFB** [astahmer/openapi-zod-client#60]
Hi and thanks for this awesome package! I currently get the error `TypeError: schema.type.toLowerCase is not a function` when trying to convert the following spec

https://dsfinvk.fiskaly.com/api/v1/_spec.json

The error also reproduces in the online version.

**Comment by astahmer** [comment]
hey, the error is indeed unclear 😅 
it looks like it's cause you sometimes have an array instead of a string for the `SchemaObject["type"]` like  `"type": ["object", "null"],`

not sure but I don't think this is supported by the openapi spec ?

**Comment by JarnoRFB** [comment]
Accoring to JSON Schema, which was referenced in the [OpenAPI spec](https://spec.openapis.org/oas/v3.1.0#schema-object), it seems indeed to be possible to restrict a type to an array of other types. See https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-7.6.1 . There is also an example with `"type": ["object", "boolean"],` in the spec. This is also new to me, but seems like something that should be supported.

**Comment by astahmer** [comment]
oh ok, looks cool ! 
so, just to be sure before I get started on the implementation, can you confirm that it basically acts as a `or` operator, like the `SchemaObject["oneOf"]` ?

**Comment by JarnoRFB** [comment]
Yes that's how I understand it :+1:

**Comment by JarnoRFB** [comment]
Awesome work! No need to worry about any delay, I think you are giving extremely fast help for a solo open source project! Code and the playground look good to me :+1:

**Comment by astahmer** [comment]
should be published soon !

**Comment by JarnoRFB** [comment]
I guess this can be closed as well now. Thanks again :rocket:
