### ISSUE TITLE
TODO - Fix the playground SplitPane

### ISSUE THREAD

**Issue by astahmer** [astahmer/openapi-zod-client#64]
looks like it's broken right now, not surprised as it was a home-made (tho very inspired from other projects) quick implementation from me

it would be a lot better to use a proven solution like https://react-resizable-panels.vercel.app/

**Comment by astahmer** [comment]
hey, thank you ! 
you need to fork the repository, make the changes on your fork and then you should be able to make a PR out of it

![Screenshot 2023-02-07 at 14 07 15](https://user-images.githubusercontent.com/47224540/217253122-6404eb62-3fa8-45e7-9cce-e815dc266319.png)

**Comment by robotkutya** [comment]
cool! :)

https://github.com/astahmer/openapi-zod-client/pull/84
